"""add action plan to interview evaluations

Revision ID: 1e88d30b643e
Revises: 4f003ad874f3
Create Date: 2026-08-29 23:22:52.728283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e88d30b643e'
down_revision: Union[str, Sequence[str], None] = '4f003ad874f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "interview_evaluations",
        sa.Column(
            "action_plan",
            sa.Text(),
            nullable=False,
            server_default="[]",
        ),
    )

    op.alter_column(
        "interview_evaluations",
        "action_plan",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_evaluations', 'action_plan')
    # ### end Alembic commands ###
