"""add extracted topics to resumes

Revision ID: 7c62a571aef2
Revises: 1e88d30b643e
Create Date: 2026-09-02 19:12:41.233209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c62a571aef2'
down_revision: Union[str, Sequence[str], None] = '1e88d30b643e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resumes',
        sa.Column(
            'extracted_topics',
            sa.JSON(),
            nullable=False,
            server_default='[]',
        ),
    )

    op.alter_column(
        'resumes',
        'extracted_topics',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_topics')
    # ### end Alembic commands ###
