"""add interview question count

Revision ID: 860f615d5f79
Revises: d68ed02822c9
Create Date: 2026-08-29 15:12:25.201308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860f615d5f79'
down_revision: Union[str, Sequence[str], None] = 'd68ed02822c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'interview_sessions',
        sa.Column(
            'question_count',
            sa.Integer(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE interview_sessions "
        "SET question_count = 10 "
        "WHERE question_count IS NULL"
    )

    op.alter_column(
        'interview_sessions',
        'question_count',
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'question_count')
    # ### end Alembic commands ###
