"""add interview progress

Revision ID: 8d8aa01c7ab1
Revises: 0b198d599f35
Create Date: 2026-08-29 16:13:31.745717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8aa01c7ab1'
down_revision: Union[str, Sequence[str], None] = '0b198d599f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "interview_sessions",
        sa.Column(
            "current_question",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE interview_sessions "
        "SET current_question = 1 "
        "WHERE current_question IS NULL"
    )

    op.alter_column(
        "interview_sessions",
        "current_question",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'current_question')
    # ### end Alembic commands ###
