"""add interview topics

Revision ID: 8e9fc3aadbad
Revises: 860f615d5f79
Create Date: 2026-08-29 15:20:30.513269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9fc3aadbad'
down_revision: Union[str, Sequence[str], None] = '860f615d5f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'interview_sessions',
        sa.Column(
            'topics',
            sa.ARRAY(sa.String()),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE interview_sessions "
        "SET topics = ARRAY['general'] "
        "WHERE topics IS NULL"
    )

    op.alter_column(
        'interview_sessions',
        'topics',
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'topics')
    # ### end Alembic commands ###
